### ISSUE TITLE
how to handle the text "[0m[91mnpm[0m[91m [0m[91m"

### ISSUE THREAD

**Issue by ozbillwang** [samueldg/bamboo-log-enhancer#7]
This is really great extension and help me a lot when I need read the bamboo logs

There are a lot of text as `[0m[91mnpm[0m[91m [0m[91m` how to handle these with this extension?

![screen shot 2018-03-13 at 11 29 07 am](https://user-images.githubusercontent.com/8954908/37316192-ceeb9ca0-26b1-11e8-9826-21e57421eefc.png)

**Comment by samueldg** [comment]
Hey @ozbillwang, thanks for the kind words :)

The extension doesn't try to be smart with the actual contents of the logs, it really only colors the output as a function of the first word (build, error, etc.) to easily spot blocks of errors, for instance.

I don't use Bamboo anymore, but when I did I often just ran whatever programs in my build using some flags to tell it not to use human-friendly output (like progress bars, colors, highlights, etc.)

I know with `npm` you have `--no-color` available, and probably other tweaks available.

**Comment by ozbillwang** [comment]
Thanks to explain. 

I am surprise Bamboo itself still can't handle the build output colour properly until now (I used it 5 years before, then move on to other pipeline tools).
