### ISSUE TITLE
can we get a firefox version?

### ISSUE THREAD

**Issue by pmcanseco** [samueldg/bamboo-log-enhancer#8]

**Comment by samueldg** [comment]
I'm open to the idea! I'm a complete noob with Firefox extensions, so I'd need to look into it first.

**Comment by samueldg** [comment]
@pmcanseco I just uploaded the extension to Firefox: https://addons.mozilla.org/en-US/firefox/addon/bamboo-log-enhancer/

I thought it would involve some port, but actually this extension is so simple it was compatible out-of-the-box! 😅

Hope this is still relevant to you!

**Comment by pmcanseco** [comment]
It sure is, much appreciated!
